name: "Middleman build and deploy to github pages"

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache build directory
        uses: actions/cache@v3
        with:
          key: build-dir-cache-v1
          path: |
            ./build

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Middleman build
        run: bundle exec middleman build
        env:
          BENTO_WRITE_KEY: ${{ secrets.BENTO_WRITE_KEY }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

